#!/usr/bin/env bash
#
# Turn an alias-proposer run into a reviewable pull request — or into nothing at all.
#
# The proposer (tennis_model/src/tennis_model/data/alias_proposer.py) writes config.py edits
# for identity mismatches that survived its falsifier. This script is the last automated
# step before a human: it branches, commits, and opens a PR. It deliberately CANNOT merge.
#
# Lives as a script rather than an inline `run:` block because AGENTS.md requires every
# `gh`-invoking branch be reachable by tests/test_workflow_alerts.py under a stubbed `gh` —
# the decision "does a bot open a PR against the repo whose master branch IS production"
# is exactly the kind that must be pinned by a test, not reviewed once in YAML.
#
# Inputs (env):
#   CONFIG_PATH   the file the proposer may have edited (default the real config.py)
#   BODY_FILE     markdown PR body written by the proposer (accepted + rejected + sources)
#   BRANCH        branch name to push
#   BASE          base branch for the PR (default master)
#   DRY_RUN       "1" -> do everything except push/PR (used to exercise the branch logic)
#
# Branches:
#   config.py unchanged  -> exit 0, no branch, no PR, no `gh` call. The overwhelmingly
#                           common case: a quiet week is not an event.
#   missing body file    -> exit 0, no PR. A patch without its evidence is unreviewable,
#                           and opening it anyway would train the reviewer to rubber-stamp.
#   config.py changed    -> branch + commit + push + `gh pr create`, never `gh pr merge`.
#
# Exit code is 0 in every branch. This job has no consumers downstream and never touches the
# site; a red run here would page the owner for something that cannot have broken anything.
set -e

CONFIG_PATH="${CONFIG_PATH:-tennis_model/src/tennis_model/config.py}"
BODY_FILE="${BODY_FILE:-/tmp/alias-pr-body.md}"
BRANCH="${BRANCH:-alias-proposer/$(date -u +%Y-%m-%d)}"
BASE="${BASE:-master}"

if git diff --quiet -- "$CONFIG_PATH"; then
  echo "no config change -> nothing to propose"
  exit 0
fi

if [ ! -s "$BODY_FILE" ]; then
  echo "::warning::config changed but no proposal body was written — refusing to open an unreviewable PR"
  git checkout -- "$CONFIG_PATH"
  exit 0
fi

N=$(git diff --numstat -- "$CONFIG_PATH" | awk '{print $1}')
echo "proposing ${N:-?} added line(s) in $CONFIG_PATH"

if [ "${DRY_RUN:-}" = "1" ]; then
  echo "dry run -> not pushing"
  exit 0
fi

git config user.name  "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -b "$BRANCH"
git add "$CONFIG_PATH"
git commit -m "chore(aliases): propose identity fixes the falsifier could not refute

Generated by the alias proposer. Every entry is a proposal: the runtime is
unchanged and stays fully deterministic. Review the evidence in the PR body
before merging — merging is what adopts it."
git push --force-with-lease origin "$BRANCH"

# `gh pr create`, never `gh pr merge`. Pushing to master IS the production deploy in this
# repo (AGENTS.md), so an auto-merged bot PR would deploy a model-authored config change
# with no human in the loop — the one thing this whole design exists to prevent.
gh pr create --base "$BASE" --head "$BRANCH" \
  --title "chore(aliases): proposed identity fixes ($(date -u +%Y-%m-%d))" \
  --body-file "$BODY_FILE" \
  --label alias-proposer 2>/dev/null \
  || gh pr create --base "$BASE" --head "$BRANCH" \
       --title "chore(aliases): proposed identity fixes ($(date -u +%Y-%m-%d))" \
       --body-file "$BODY_FILE"
